### ISSUE TITLE
How to display username in footer.html?

### ISSUE THREAD

**Issue by tkowalczyk** [scotch-io/meteor-slack#2]
At this moment there is always `scotch` and it is online ;)

**Comment by d4nyll** [comment]
The aim of the tutorials are to cover as many topics so that the readers understand and can extrapolate. For example, they can use the publish/subscribe methods to implement private messages, for example.

To display usernames in the footer, you can use `Meteor.user()` to get the information about the current user, for the online/away - you can use a reactive variable to test if the user has been active in the last, say 10 minutes, and for the avatar you'd probably need the [CollectionFS](https://github.com/CollectionFS/Meteor-CollectionFS) package to handle uploads.
